### ISSUE TITLE
upgrade problem

### ISSUE THREAD

**Issue by speedkup** [PeeK1e/kubeadm-upgrade#3] opened 2024-05-28 17:14 UTC
Hi,

First of all, I would like to thank you for writing this role, as it fills a much-needed gap.
However, I have encountered a problem.
I tried to upgrade from 1.25.16 to 1.26.15 with it and got stuck at this part:

```shell
TASK [upgrade-cp : kubadm plan] **************************************************************************************************************************************************
kedd 28 május 2024  16:03:19 +0200 (0:00:02.065)       0:00:32.668 ************ 
changed: [k8s-mn1]

TASK [upgrade-cp : output plan] **************************************************************************************************************************************************
kedd 28 május 2024  16:03:27 +0200 (0:00:08.382)       0:00:41.051 ************ 
ok: [k8s-mn1] => {
    "msg": "plan stdout , stderr: I0528 16:03:26.707021   20585 version.go:256] remote version is much newer: v1.30.1; falling back to: stable-1.26"
}

TASK [upgrade-cp : set fact] *****************************************************************************************************************************************************
kedd 28 május 2024  16:03:27 +0200 (0:00:00.082)       0:00:41.133 ************ 
ok: [k8s-mn1]

TASK [upgrade-cp : register plan version to dummy host] **************************************************************************************************************************
kedd 28 május 2024  16:03:27 +0200 (0:00:00.082)       0:00:41.216 ************ 
changed: [k8s-mn1]

TASK [upgrade-cp : make sure installed version equals planned version] ***********************************************************************************************************
kedd 28 május 2024  16:03:27 +0200 (0:00:00.048)       0:00:41.264 ************ 
ok: [k8s-mn1] => {
    "msg": "planned version: v0.0.0 and apt package version: 1.26.15-1.1"
}

TASK [upgrade-cp : make sure installed version equals planned version] ***********************************************************************************************************
kedd 28 május 2024  16:03:28 +0200 (0:00:00.050)       0:00:41.314 ************ 
fatal: [k8s-mn1]: FAILED! => {"changed": false, "msg": "versions not equal or you are on the latest patch of 1.26"}

PLAY RECAP ***********************************************************************************************************************************************************************
k8s-mn1                    : ok=18   changed=8    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

I was only able to complete the run by creating a K(S_TOKEN_HOLDER.yml file in the inventory host_vars directory and adding this variable to it:
plan_version: "v1.26.15"

After that, the upgrade went through. Do you have any idea about this, or is it supposed to work this way?

Thank you in advance for your help.

**Comment by PeeK1e** [comment] 2024-05-28 18:04
Hey,
and thanks for using it :smile: 
 
Since 1.25 is a bit older it will take some time to setup a test env and digging into archived docs again. 
My best guess would be, that since the `-o` option of `kubeadm upgrade plan` is not stable and still marked as a beta feature, it may happen that the output will just be changed and my "pipe magic" wont work on older **or** even newer versions (as seen in v1.30) :slightly_smiling_face: 

Could you send me the `group_vars` from your run. When I find some time I'll try to reproduce it on a small test cluster.
Also if you're on a test env with that node/cluster could you run the playbook with `-vvv` to get the verbose output and see what the `kubeadm upgrade plan` command returned?

**Comment by speedkup** [comment] 2024-05-30 09:54
Hello,

Yesterday, I retested your role and found out that I made a mistake because I did not provide the full hostname in the inventory. You even mentioned it in the README. So, once I provided the correct hostnames, the upgrade from v1.25 to v1.26 and onwards worked perfectly. I tested it up to version 1.28.

I also added an etcd backup at the very beginning.

Sorry for the inconvenience. Please close the ticket.

Thank you very much for your help!

**Comment by PeeK1e** [comment] 2024-05-31 12:38
Glad to hear that it worked, I might have to mark this a bit better in the Readme ;)

If you'd like you can commit your code to backup the etcd here as PR. Will gladly accept it!

**Closed as completed** 2024-05-31 12:38 UTC
Labels: bug
